
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "46bab59782eb0930854a0a73640b011b4cf4b6cf",
 "version": "1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
